### PR TITLE
Fix the configuration processing to support the XML format

### PR DESCRIPTION
**Pull request by stof**
- handle the prototyped nodes properly for the XML specificities
- disable the key normalization for prototyped nodes given that this is a key defined by the user (this is not done by default in Symfony only because of BC reasons).

### CODE REVIEW

**Comment by stof** [comment]
Currently, the XML namespace is still the default one generated by symfony: ``http://example.org/schema/dic/swarrot``.
It may be better to change it to a better XML namespace (changing it now would not be considered as a BC break IMO, given that the XML format is broken before this PR anyway)

**Comment by odolbeau** [comment]
Good to know. I really need to deep into the whole Configuration process... :/

Why do you want to change the generated namespace? Using the default one is not recommended?

**Comment by stof** [comment]
@odolbeau The generated one is here so that all extension have an XML namespace automatically, allowing them to be configured in XML already (as long as you don't have prototyped nodes in your Configuration class, there is nothing special to add for XML).
However, the ``example.org`` domain may not be the best choice for the XML namespace. And then, changing the XML namespace in the future is a hard BC break (no way to provide a BC layer for it at all). This is why it would be a good time to decide between keeping the existing generated one or use a better one

**Comment by odolbeau** [comment]
I don't have any preference. :)
I have the domain swarrot.io if needed.

Can we use something like `http://swarrot.io/schema/dic/swarrot`?

**Comment by stof** [comment]
@odolbeau looks good to me

**Comment by stof** [comment]
here we go. The second commit is changing the XML namespace and also implements the XSD, allowing XML lovers to get autocompletion in their IDEs

**Comment by odolbeau** [comment]
:+1:

**Pull request merged**
