### PR TITLE
Custom processor doc

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
Don't merge yet, I'm not done implementing my custom processor and would like to add some commits.

**Comment by greg0ire** [comment]
All good now :)

**Comment by odolbeau** [comment]
Thanks!
Could you please rebase your branch? I updated the `Extension` in order to support sf4 and corrected the typo.

**Comment by greg0ire** [comment]
@odolbeau done

**Comment by odolbeau** [comment]
Thanks!

**Pull request merged**
